# Generated by Django 4.1.1 on 2022-11-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteReservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(db_column='Number', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='imageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=255)),
                ('Tipo', models.CharField(max_length=255)),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('Celular', models.CharField(max_length=255)),
                ('FechaInicio', models.DateField()),
                ('FechaFinal', models.DateField()),
                ('Observaciones', models.CharField(max_length=255)),
                ('Patente', models.CharField(max_length=8)),
            ],
        ),
    ]
