# Generated by Django 4.1.3 on 2022-11-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='imagen',
            field=models.TextField(max_length=15000),
        ),
    ]
