CREATE DATABASE USUARIOS;
CREATE DATABASE VISITAS;

USE USUARIOS;
CREATE TABLE IF NOT EXISTS USUARIOS(ID INT, RUT VARCHAR(10), NOMBRE VARCHAR(30)
                                    , APELLIDO VARCHAR(30), TIPO INT, CORREO VARCHAR(50)
                                    , CLAVE VARCHAR(64), ID_DOMICILIO INT, CONDOMINIO VARCHAR(20));

CREATE TABLE IF NOT EXISTS CODE_USUARIOS(RUT VARCHAR(10), CORREO VARCHAR(50), CODE VARCHAR(64));