# Generated by Django 4.1.1 on 2022-10-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=255)),
                ('Tipo', models.CharField(max_length=255)),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('Celular', models.CharField(max_length=255)),
                ('FechaInicio', models.DateField()),
                ('FechaFinal', models.DateField()),
                ('Observaciones', models.CharField(max_length=255)),
            ],
        ),
    ]
