# Generated by Django 4.1.1 on 2022-10-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteReservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(db_column='Number', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='visits',
            name='Patente',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
